In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed\hotel_bookings_encoded.csv"
)

df.shape

(87359, 29)

In [3]:
df.head()

,hotel,lead_time,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,total_stay_nights,total_guests,booking_changed,has_previous_cancellation,special_request_flag,is_canceled
0,1,342,5,0,0,2,0.0,0,0,135,...,2,0.0,0,0,0,2.0,1,0,0,0
1,1,737,5,0,0,2,0.0,0,0,135,...,2,0.0,0,0,0,2.0,1,0,0,0
2,1,7,5,0,1,1,0.0,0,0,59,...,2,75.0,0,0,1,1.0,0,0,0,0
3,1,13,5,0,1,1,0.0,0,0,59,...,2,75.0,0,0,1,1.0,0,0,0,0
4,1,14,5,0,2,2,0.0,0,0,59,...,2,98.0,0,1,2,2.0,0,0,1,0

## Train-Test Split

The dataset is divided into training and testing sets.

The training data is used to build the model, while the testing data is used to evaluate model performance.

In [4]:
X = df.drop("is_canceled", axis=1)
y = df["is_canceled"]

X.shape, y.shape

((87359, 28), (87359,))

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(69887, 28)
(17472, 28)
(69887,)
(17472,)

## Feature Scaling

Feature scaling standardizes numerical values so that machine learning algorithms perform efficiently.

In [7]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(69887, 28)
(17472, 28)

In [11]:
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)

X_train_scaled.head()

,hotel,lead_time,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,deposit_type,customer_type,adr,required_car_parking_spaces,total_of_special_requests,total_stay_nights,total_guests,booking_changed,has_previous_cancellation,special_request_flag
0,1.252106,-0.556028,-1.238988,0.967517,0.182390,0.195309,-0.303176,-0.094432,-0.515075,-0.802732,...,-0.11246,-0.105737,2.114725,-0.297929,0.368703,0.496679,-0.029581,-0.471909,-0.139016,1.008926
1,-0.798654,-0.927934,-1.238988,-0.974269,0.182390,0.195309,-0.303176,-0.094432,-0.515075,1.075512,...,-0.11246,-3.884631,0.567817,3.255815,1.574936,-0.227925,-0.029581,2.119051,-0.139016,1.008926
2,-0.798654,-0.834957,-0.950775,-0.974269,-0.791979,0.195309,-0.303176,-0.094432,2.260976,1.075512,...,-0.11246,-0.105737,-2.139273,-0.297929,1.574936,-0.952528,-0.029581,2.119051,-0.139016,1.008926
3,-0.798654,-0.730359,-0.662561,-0.003376,-0.791979,0.195309,1.887030,-0.094432,-0.515075,1.075512,...,-0.11246,-0.105737,0.466047,-0.297929,1.574936,-0.590227,1.209069,-0.471909,-0.139016,1.008926
4,-0.798654,-0.474674,-0.950775,-0.003376,-0.304794,1.752230,-0.303176,-0.094432,-0.515075,-0.690932,...,-0.11246,-0.105737,-0.302726,-0.297929,0.368703,-0.227925,1.209069,-0.471909,-0.139016,1.008926

In [12]:
X_train_scaled.to_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed\X_train_scaled.csv",
    index=False
)

X_test_scaled.to_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed\X_test_scaled.csv",
    index=False
)

y_train.to_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed\y_train.csv",
    index=False
)

y_test.to_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed\y_test.csv",
    index=False
)

print("Train and Test datasets saved successfully.")

Train and Test datasets saved successfully.

## Findings

- Separated features and target variable.
- Split the dataset into 80% training and 20% testing.
- Applied StandardScaler to numerical features.
- Saved scaled datasets for machine learning.

## Day 3 Conclusion

The dataset was successfully divided into training and testing sets.

Feature scaling was applied to standardize the data, ensuring that all variables contribute equally during machine learning model training.

The processed datasets are now ready for building classification models.